### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by zjm199502** [delvendahl/miniML#1]
Hi dear sir/madam,

Thanke you for your work and i am trying to use miniML to analyze mEPSC data.
I have got problem in installation miniML. It goes well when i use pip to install miniML. But jupyterlab failed to import this module as : 
![image](https://github.com/delvendahl/miniML/assets/60344825/9c438750-a88e-4384-95aa-fddfe3d8de39)

I have checked the installed document in my conda package, it show as : 
![image](https://github.com/delvendahl/miniML/assets/60344825/5f1d9f17-8b10-437c-be9b-8f10590ff82c)

Do you have any idea on this issue?

Thank you very much!

Jinming Zhang

**Comment by poneil-UZH** [comment]
Hi Jinming

miniML is not available via pip install. Instead, we have defined the required classes in the miniML.py file.
The imports:

import sys
sys.path.append('../../miniML/core/')
from miniML import MiniTrace, EventDetection

import those classes from the .py file. You need to clone the repository, then you can import the classes from the core directory and use them in the tutorial.ipynb file. I hope this helps.

**Comment by IKMORLEY** [comment]
Hi there. When I cloned the repository there were no setup or to pull from, so when i tried: import sys
sys.path.append('../../core/')
from miniML import MiniTrace, EventDetection
from miniML_plot_functions import miniML_plots

The end result was an error that said no module named miniML
