### ISSUE TITLE
How to read HEKA file

### ISSUE THREAD

**Issue by Alchimst** [delvendahl/miniML#3]

**Comment by delvendahl** [comment]
Data from HEKA .dat files can be loaded using the **from_heka_file()** method of miniML's MiniTrace objects. You need to specify the file path and the name of the PGF sequence to be loaded. Optional parameters include scaling factor and the option to exclude specific series or sweeps (see docstring in the miniML.py file). 

Here's an example of how to use the **from_heka_file()** method:

```
path_to_file = '/path/to/file'
name_of_PGF = 'my_PGF_sequence'
scaling_factor = 1e12
unit = 'pA'

trace = MiniTrace.from_heka_file(filename=path_to_file,
                                 rectype=name_of_PGF,
                                 scaling=scaling_factor,
                                 unit=data_unit)
```


You can also use miniML's HekaReader to read and print all PGF sequences for a given file:

```
import FileImport.HekaReader as heka
        
path_to_file = '/path/to/file'
bundle = heka.Bundle(path_to_file)

bundle_series = dict()
for i, SeriesRecord in enumerate(bundle.pul[group].children):
    bundle_series.update({i: SeriesRecord.Label})

print(bundle_series)
```
