### ISSUE TITLE
How to analyze a subsection of .abf?

### ISSUE THREAD

**Issue by ms-cassafrass** [delvendahl/miniML#6]
Hello, I am wondering if there is a way to run a portion of a file and not the whole file? Some of my recordings have weird noise at the beginning or I'll start to loose a cell at the end and only want to use the beginning half of the recording. It would be nice to either be able to crop a recording or tell miniML to only look at a portion of the recording. Do you know of a way to do this?

**Comment by ms-cassafrass** [comment]
I think this is working for me

#cropping a recording-- find new starting point in seconds and multiply by sampling rate/ms (s*100000)
starting_point_seconds = ###add number here in seconds
starting_point = starting_point_seconds * 100000
ending_point_seconds = ###add number here in seconds
ending_point = ending_point_seconds * 100000

trace.data = trace.data[starting_point:ending_point]

**Comment by poneil-UZH** [comment]
If you want to exclude multiple small stretches, something like this should work:

import numpy as np
t1, t2 = 0, 30 # get the first 30 s
p1, p2 = int(t1/trace.sampling), int(t2/trace.sampling)
stretch_1 = trace.data[p1:p2]

t1, t2 = 90, 120 # get the last 30 s
p1, p2 = int(t1/trace.sampling), int(t2/trace.sampling)
stretch_2 = trace.data[p1:p2]

trace.data = np.concatenate((stretch_1, stretch_2))

Here, I take the first 30 s (0 to 30) and last 30s (90 to 120) from a 2 minute recording. You could e.g. do (0, 2), (3, 11), (12, 120 (or however the long recording is)) if you get some weird noise or an unstable recording in the stretches between 2 and 3 s and 11 and 12 s.

Hope this helps!

**Comment by delvendahl** [comment]
miniML's MiniTrace Objects represent data as standard NumPy 1d-arrays. Accordingly, regular NumPy indexing can be used to crop the data in various flexible ways. The two previous posts illustrate this nicely. I therefore close this issue.
